<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.0.4
 */

/**
 * Database `ftt_online`
 */

/* `ftt_online`.`tour_packages` */
$tour_packages = array(
  array('id' => '1','location' => '1','vender_id' => '2','package_name' => 'himanchl','nights' => '2','price' => '313','image' => 'C:\\Users\\shads\\AppData\\Local\\Temp\\phpA915.tmp','gallery_image' => 'C:\\Users\\shads\\AppData\\Local\\Temp\\phpA926.tmp','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'wdwe','payment_policy' => 'adad','cancellation_policies' => 'dwedw','terms_and_conditions' => 'adad','about_destination' => 'wdfdwea','day_wise_itinerary' => 'sdsd','departure_dates' => '2012-12-12','created_at' => '2022-01-14 05:52:46','updated_at' => '2022-01-14 05:52:46','deleted_at' => NULL),
  array('id' => '2','location' => '1','vender_id' => '2','package_name' => 'himanchl','nights' => '0','price' => '0','image' => NULL,'gallery_image' => NULL,'amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'wdwe','payment_policy' => 'kjbjkb','cancellation_policies' => 'kbkjb','terms_and_conditions' => 'bkjjbk','about_destination' => 'bkb','day_wise_itinerary' => NULL,'departure_dates' => NULL,'created_at' => '2022-01-17 05:24:23','updated_at' => '2022-01-17 05:24:23','deleted_at' => NULL),
  array('id' => '3','location' => '1','vender_id' => '2','package_name' => 'himanchl','nights' => '2','price' => '0','image' => NULL,'gallery_image' => NULL,'amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'wdwe','payment_policy' => 'kbkjb','cancellation_policies' => 'kbjkjj','terms_and_conditions' => 'jknj','about_destination' => 'kjj','day_wise_itinerary' => NULL,'departure_dates' => NULL,'created_at' => '2022-01-17 05:37:21','updated_at' => '2022-01-17 05:37:21','deleted_at' => NULL),
  array('id' => '4','location' => '1','vender_id' => '2','package_name' => 'himanchl','nights' => '2','price' => '32','image' => NULL,'gallery_image' => NULL,'amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'wdwe','payment_policy' => 'bbib','cancellation_policies' => 'bubui','terms_and_conditions' => 'bi','about_destination' => 'hbjbi','day_wise_itinerary' => 'hbb','departure_dates' => NULL,'created_at' => '2022-01-17 05:40:46','updated_at' => '2022-01-17 05:40:46','deleted_at' => NULL),
  array('id' => '5','location' => '1','vender_id' => '2','package_name' => 'himanchl','nights' => '2','price' => '313','image' => 'C:\\Users\\shads\\AppData\\Local\\Temp\\php3B7.tmp','gallery_image' => 'C:\\Users\\shads\\AppData\\Local\\Temp\\php3B8.tmp','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'wdwe','payment_policy' => 'bjb','cancellation_policies' => 'ihb','terms_and_conditions' => 'jbjbu','about_destination' => 'njnhu','day_wise_itinerary' => 'ubuuhu','departure_dates' => '','created_at' => '2022-01-17 05:49:47','updated_at' => '2022-01-17 05:49:47','deleted_at' => NULL),
  array('id' => '6','location' => '1','vender_id' => '2','package_name' => 'himanchl','nights' => '0','price' => '0','image' => 'C:\\Users\\shads\\AppData\\Local\\Temp\\php2F60.tmp','gallery_image' => 'C:\\Users\\shads\\AppData\\Local\\Temp\\php2F61.tmp','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'wdwe','payment_policy' => '','cancellation_policies' => '','terms_and_conditions' => '','about_destination' => '','day_wise_itinerary' => '','departure_dates' => 'adasd','created_at' => '2022-01-17 05:53:15','updated_at' => '2022-01-17 05:53:15','deleted_at' => NULL),
  array('id' => '7','location' => '1','vender_id' => '2','package_name' => '','nights' => '0','price' => '0','image' => '1642420486_77bf42c90689c77c7ec9.jpg','gallery_image' => '1642420486_74609e7a8fcfc3ec8508.jpg','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => '','payment_policy' => '','cancellation_policies' => '','terms_and_conditions' => '','about_destination' => '','day_wise_itinerary' => '','departure_dates' => '','created_at' => '2022-01-17 05:54:46','updated_at' => '2022-01-17 05:54:46','deleted_at' => NULL),
  array('id' => '8','location' => '1','vender_id' => '2','package_name' => 'himanchl','nights' => '0','price' => '0','image' => '1642420602_db91bcc1094059f5b653.jpg','gallery_image' => '1642420602_a69c1d09dff4c05fb145.jpg','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'wdwe','payment_policy' => '','cancellation_policies' => '','terms_and_conditions' => '','about_destination' => '','day_wise_itinerary' => '','departure_dates' => '','created_at' => '2022-01-17 05:56:42','updated_at' => '2022-01-17 05:56:42','deleted_at' => NULL),
  array('id' => '9','location' => '1','vender_id' => '2','package_name' => '','nights' => '0','price' => '0','image' => '1642421936_710cfea57dfdf8a90ffc.jpg','gallery_image' => '1642421936_7c2a869065833ad51c2d.jpg','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => '','payment_policy' => '','cancellation_policies' => '','terms_and_conditions' => '','about_destination' => '','day_wise_itinerary' => '','departure_dates' => '','created_at' => '2022-01-17 06:18:56','updated_at' => '2022-01-17 06:18:56','deleted_at' => NULL),
  array('id' => '10','location' => '1','vender_id' => '2','package_name' => '','nights' => '0','price' => '0','image' => '1642422656_a0e649e5733fab5a23f8.png','gallery_image' => '1642422656_3d02bc35b1141b4c2d82.jpg','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => '','payment_policy' => '','cancellation_policies' => '','terms_and_conditions' => '','about_destination' => '','day_wise_itinerary' => '','departure_dates' => '','created_at' => '2022-01-17 06:30:56','updated_at' => '2022-01-17 06:30:56','deleted_at' => NULL),
  array('id' => '11','location' => '1','vender_id' => '2','package_name' => 'Manali','nights' => '5','price' => '4500','image' => '1642429683_1d4ad07d8c501d581dad.png','gallery_image' => '1642429683_a7f6e575e4cd9ecf1287.png','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '0','include_visit_best_place' => '0','include_additional_services' => '0','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'Manali is awesome place for adventure trip.','payment_policy' => 'Policy','cancellation_policies' => 'CP','terms_and_conditions' => 'TOC','about_destination' => 'Manali is awesome place for adventure trip.','day_wise_itinerary' => 'Booking','departure_dates' => '19-01-2022','created_at' => '2022-01-17 08:28:03','updated_at' => '2022-01-17 08:28:03','deleted_at' => NULL),
  array('id' => '12','location' => NULL,'vender_id' => '0','package_name' => 'Manali','nights' => '6','price' => '6','image' => '1642512727_34e8bce6342e6b451716.png','gallery_image' => '1642512727_bd30b5630317c683fa55.png','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '','include_visit_best_place' => '','include_additional_services' => '','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'asdasda','payment_policy' => 'asassa','cancellation_policies' => 'wsqwsq','terms_and_conditions' => 'swsq','about_destination' => 'asasqs','day_wise_itinerary' => 'Booking','departure_dates' => '01/21/2022','created_at' => '2022-01-18 07:32:07','updated_at' => '2022-01-18 07:32:07','deleted_at' => NULL),
  array('id' => '13','location' => NULL,'vender_id' => '0','package_name' => 'Manali','nights' => '7','price' => '6','image' => '1642513026_96df8c552558eeec26c2.png','gallery_image' => '1642513026_38eecf2ef9be3ea66c57.png','amenities_accept_credit_card' => '','amenities_car_parking' => '','amenities_coupons' => '','amenities_resturent' => '','amenities_smoking' => '','amenities_wireless_internet' => '','include_pick_and_drop' => '','include_meal_per_day' => '','include_dinner_music_event' => '','include_visit_best_place' => '','include_additional_services' => '','include_insurance' => '','include_food_drinks' => '','include_tickets' => '','overview' => 'dgdfgdsg','payment_policy' => 'cdscsd','cancellation_policies' => 'sdsfs','terms_and_conditions' => 'sdcsdcsd','about_destination' => 'sdsdf','day_wise_itinerary' => 'Booking','departure_dates' => '02/01/2022','created_at' => '2022-01-18 07:37:06','updated_at' => '2022-01-18 07:37:06','deleted_at' => NULL)
);
